AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Well-Architected Serverless Application

Resources:
  Service1Function:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: functions/service1/
      Handler: handler.handler
      Runtime: nodejs14.x
      Architectures:
        - x86_64
      Events:
        ApiEvent:
          Type: Api
          Properties:
            Path: /service1
            Method: get